- type: job
  id: Chemist
  name: job-name-chemist
  description: job-description-chemist
  playTimeTracker: JobChemist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 5h
  startingGear: ChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-cmo
  whitelisted: true # collard-NoPlaytimeRequirements
  access:
  - Medical
  - Chemistry
#  - Maintenance || collard-NoMaintAccess

- type: startingGear
  id: ChemistGear
  equipment:
    id: ChemistryPDA
    # ears: ClothingHeadsetMedical || collard-Headset1984
    belt: ChemBag
    pocket1: HandLabeler
    eyes: ClothingEyesGlassesChemical
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ChemistChameleonOutfit
  job: Chemist
  equipment:
    head: ClothingHeadHatBeretMedic
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLabChem
    gloves: ClothingHandsGlovesLatex
