using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.FlavorText
{
    [GenerateTypedNameReferences]
    public sealed partial class FlavorText : Control
    {
        public Action<string>? OnFlavorTextChanged;
        public Action<string>? OnRoundstartPoseTextChanged; // collard-DetailExaminableGlowup

        public FlavorText()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            var loc = IoCManager.Resolve<ILocalizationManager>();
            CFlavorTextInput.Placeholder = new Rope.Leaf(loc.GetString("flavor-text-placeholder"));
            CFlavorTextInput.OnTextChanged += _ => FlavorTextChanged();
            CRoundstartPoseInput.Placeholder = new Rope.Leaf(loc.GetString("posing-content-none")); // collard-DetailExaminableGlowup
            CRoundstartPoseInput.OnTextChanged += _ => RoundstartPoseTextChanged(); // collard-DetailExaminableGlowup
        }

        public void FlavorTextChanged()
        {
            OnFlavorTextChanged?.Invoke(Rope.Collapse(CFlavorTextInput.TextRope).Trim());
        }

        // collard-DetailExaminableGlowup-start
        public void RoundstartPoseTextChanged()
        {
            OnRoundstartPoseTextChanged?.Invoke(Rope.Collapse(CRoundstartPoseInput.TextRope).Trim());
        }
        // collard-DetailExaminableGlowup-end
    }
}
