- type: entity
  abstract: true
  parent: [SolutionFood, SolutionToolSmall, Clothing, BaseSlicingRefinable]
  id: ClothingUnderwearBottomBase
  name: based underwearb
  description: "baseunderwear"
  components:
  - type: Sprite
    state: icon
  - type: Item
    size: Tiny
  - type: Clothing
    quickEquip: true
    slots: [underwearb]
  - type: ToolRefinable
    refineResult:
    - id: MaterialCloth1
      amount: 1
  - type: PhysicalComposition
    materialComposition:
      Cloth: 50
  - type: Edible
    requiresSpecialDigestion: true
  - type: Solution
    solution:
      reagents:
      - ReagentId: Fiber
        Quantity: 10
  - type: Tag
    tags:
      - underwearb
      - ClothMade
      - Recyclable

- type: entity
  abstract: true
  parent: [SolutionFood, SolutionToolSmall, Clothing, BaseSlicingRefinable]
  id: ClothingUnderwearTopBase
  name: based underweart
  description: "baseunderwear"
  components:
  - type: Sprite
    state: icon
  - type: Item
    size: Tiny
  - type: Clothing
    quickEquip: true
    slots: [underweart]
  - type: ToolRefinable
    refineResult:
    - id: MaterialCloth1
      amount: 1
  - type: PhysicalComposition
    materialComposition:
      Cloth: 50
  - type: Edible
    requiresSpecialDigestion: true
  - type: Solution
    solution:
      reagents:
      - ReagentId: Fiber
        Quantity: 10
  - type: Tag
    tags:
      - underweart
      - ClothMade
      - Recyclable

- type: entity
  abstract: true
  parent: [SolutionFood, SolutionToolSmall, Clothing, BaseSlicingRefinable]
  id: ClothingUnderwearSocksBase
  name: based socks
  description: "baseunderwear"
  components:
  - type: Sprite
    state: icon
  - type: Item
    size: Tiny
  - type: Clothing
    quickEquip: true
    slots: [socks]
  - type: ToolRefinable
    refineResult:
    - id: MaterialCloth1
      amount: 1
  - type: PhysicalComposition
    materialComposition:
      Cloth: 50
  - type: Edible
    requiresSpecialDigestion: true
  - type: Solution
    solution:
      reagents:
      - ReagentId: Fiber
        Quantity: 10
  - type: Tag
    tags:
      - socks
      - ClothMade
      - Recyclable
