using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Client.Collard.UserInterface.Systems.Ghost.Controls;
using Robust.Shared.Timing;
using Robust.Shared.Configuration;
using Content.Shared.CCVar;

namespace Content.Client.UserInterface.Systems.Ghost.Widgets;

[GenerateTypedNameReferences]
public sealed partial class GhostGui : UIWidget
{

    // collard-GhostRespawn-start
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    [Dependency] private readonly IConfigurationManager _configurationManager = default!;

    private TimeSpan? _timeOfDeath;
    private float _minTimeToRespawn;
    public GhostRespawnRulesWindow RespawnRulesWindow { get; }
    // collard-GhostRespawn-end
    public GhostTargetWindow TargetWindow { get; }

    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? GhostRolesPressed;
    public event Action? GhostRespawnPressed; // collard-GhostRespawn
    private int _prevNumberRoles;

    public GhostGui()
    {
        RobustXamlLoader.Load(this);

        TargetWindow = new GhostTargetWindow();
        RespawnRulesWindow = new GhostRespawnRulesWindow(); // collard-GhostRespawn

        MouseFilter = MouseFilterMode.Ignore;

        GhostWarpButton.OnPressed += _ => RequestWarpsPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesButton.StyleClasses.Remove(StyleBase.ButtonCaution);
        GhostRespawnButton.OnPressed += _ => RespawnRulesWindow.OpenCentered(); // collard-GhostRespawn
        RespawnRulesWindow.RespawnButton.OnPressed += _ => GhostRespawnPressed?.Invoke(); // collard-GhostRespawn
    }

    public void Hide()
    {
        TargetWindow.Close();
        RespawnRulesWindow.Close(); // collard-GhostRespawn
        Visible = false;
    }

    // collard-GhostRespawn-start
    public void UpdateRespawn(TimeSpan? todd)
    {
        if (todd != null)
        {
            _timeOfDeath = todd;
            _minTimeToRespawn = _configurationManager.GetCVar(CCVars.RespawnTime);
        }
    }
    // collard-GhostRespawn-start

    public void Update(int? roles, bool? canReturnToBody, TimeSpan? timeOfDeath, float minTimeToRespawn)
    {
        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;
        _timeOfDeath = timeOfDeath; // collard-GhostRespawn
        _minTimeToRespawn = minTimeToRespawn; // collard-GhostRespawn

        if (roles != null)
        {
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", roles));

            if (roles > _prevNumberRoles)
            {
                GhostRolesButton.StyleClasses.Add(StyleBase.ButtonCaution);
            }

            _prevNumberRoles = (int)roles;
        }

        TargetWindow.Populate();
    }

    // collard-GhostRespawn-start
    protected override void FrameUpdate(FrameEventArgs args)
    {
        if (_timeOfDeath is null)
        {
            GhostRespawnButton.Text = Loc.GetString("ghost-gui-respawn-button-denied", ("time", "disabled"));
            GhostRespawnButton.Disabled = true;
            return;
        }
        var delta = (_minTimeToRespawn - _gameTiming.CurTime.Subtract(_timeOfDeath.Value).TotalSeconds);
        if (delta <= 0)
        {
            GhostRespawnButton.Text = Loc.GetString("ghost-gui-respawn-button-allowed");
            GhostRespawnButton.Disabled = false;
        }
        else
        {
            GhostRespawnButton.Text = Loc.GetString("ghost-gui-respawn-button-denied", ("time", $"{delta:f1}"));
            GhostRespawnButton.Disabled = true;
        }
    }
    // collard-GhostRespawn-end

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            TargetWindow.Dispose();
        }
    }
}
