using System.Buffers;
using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.Access.Components;
using Content.Shared.CCVar;
using Content.Shared.Collard.Grill;
using Content.Shared.Security.Components;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.Timing;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Robust.Shared.Toolshed.Commands.Values;

namespace Content.Client.Collard.Grill.UI;

[GenerateTypedNameReferences]
public sealed partial class ClamshellGrillMenu : FancyWindow
{
    [Dependency] private IConfigurationManager _cfgManager = default!;
    [Dependency] private IClientGameTiming _timing = default!;

    public event Action<string, float, float>? OnProgramConfigurationComplete;

    public event Action<GrillProgram>? OnCookingStarted;
    public event Action? OnCookingCancelled;

    public event Action<GrillProgram>? OnDeleteProgram;
    public event Action<bool, bool>? OnOpenPlaten;
    public event Action? OnPopulatePrograms;
    public event Action? OnMainMenuOpened;
    public event Action? OnEditorOpened;
    public event Action? OnSelectorOpened;

    public event Action? OnUpdateTime;

    public event Action? OnUpdateOverlay;
    public event Action? OnUpdatePower;

    public event Action? StopSounds;

    private GrillProgram? _selectedProgram;
    private bool _programCancelled;

    public ClamshellGrillMenu(EntityUid owner, IEntityManager entMan)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);


        Title = entMan.GetComponent<MetaDataComponent>(owner).EntityName;

        ProgramEditor.OnPressed += _ =>
        {
            EnterProgramEditor();
            OnEditorOpened?.Invoke();
        };

        PressAndGo.OnPressed += _ =>
        {
            EnterProgramSelector();
            OnSelectorOpened?.Invoke();
        };

        DeleteProgram.OnPressed += _ =>
        {
            if (_selectedProgram is null) return;
            OnDeleteProgram?.Invoke(_selectedProgram.Value);
            OnPopulatePrograms?.Invoke();
        };

        ProgBackButton.OnPressed += _ =>
        {
            OnMainMenuOpened?.Invoke();
            EnterMainMenu();
        };

        SelBackButton.OnPressed += _ =>
        {
            OnMainMenuOpened?.Invoke();
            EnterMainMenu();
        };

        StartGrillButton.OnPressed += _ =>
        {
            if (_selectedProgram is null) return;
            EnterCooking();
            OnCookingStarted?.Invoke(_selectedProgram.Value);
        };

        EnterStandby.OnPressed += _ =>
        {
            EnterStandbyWindow();
            OnCookingStarted?.Invoke(new GrillProgram("StandbyProgram", 0, 120));
        };

        ExitStandbyButton.OnPressed += _ =>
        {
            EnterProgramSelector();
            OnOpenPlaten?.Invoke(false, true);
        };

        AbortButton.OnPressed += _ =>
        {
            EnterCancellation();
            OnOpenPlaten?.Invoke(true, false);

        };

        GotItButton.OnPressed += _ =>
        {
            EnterProgramSelector();
            OnSelectorOpened?.Invoke();
            StopSounds?.Invoke();
        };

        NameLabel.SetMarkup(Loc.GetString("grill-ui-label-name"));
        TimeLabel.SetMarkup(Loc.GetString("grill-ui-label-time"));
        TemperatureLabel.SetMarkup(Loc.GetString("grill-ui-label-temp"));

        TimeEdit.Text = "10";
        TemperatureEdit.Text = "100";

        var maxIdJobLength = _cfgManager.GetCVar(CCVars.MaxIdJobLength);
        NameEdit.IsValid = val => !string.IsNullOrWhiteSpace(val) && val.Length <= maxIdJobLength;
        TimeEdit.IsValid = val => float.TryParse(val, out var f) && f >= 0;
        TemperatureEdit.IsValid = val => float.TryParse(val, out var f) && f >= 0;

        NameEdit.OnTextChanged += _ => OnTextEdit();
        TimeEdit.OnTextChanged += _ => OnTextEdit();
        TemperatureEdit.OnTextChanged += _ => OnTextEdit();
        ProgramList.OnItemSelected += OnProgramSelected;
        ProgramList.OnItemDeselected += OnProgramDeselected;


        ProgDoneButton.OnPressed += _ =>
        {
            OnProgramConfigurationComplete?.Invoke(NameEdit.Text, float.Parse(TimeEdit.Text), float.Parse(TemperatureEdit.Text));
            ProgramCreator.Visible = false;
            MainMenu.Visible = true;
        };
    }

    /// <summary>
    /// Re-populates the list of grill programs available.
    /// </summary>
    public void Populate(IEnumerable<GrillProgram> programs)
    {
        StartGrillButton.Disabled = true;
        ProgramList.Clear();

        foreach (var entry in programs)
        {
            ProgramList.AddItem(entry.Name, metadata: entry);
        }
    }

    public void UpdateTimer(TimeSpan time, float maxTime, TimeSpan startTime)
    {
        TimerLabel.Visible = !_programCancelled;
        DisposeLabel.Visible = _programCancelled;
        TimerBar.MaxValue = maxTime;
        TimerBar.Value = (float)_timing.CurTime.Subtract(startTime).TotalSeconds;
        TimerLabel.Text = ((int)time.TotalSeconds).ToString();
        StandbyTimerLabel.Text = _timing.CurTime.Subtract(startTime).ToString("hh':'mm':'ss");
    }

    public void UpdateOverlay(bool overlay = false)
    {
        PlatenMovingOverlay.Visible = overlay;
    }

    public void UpdatePower(bool power = false)
    {
        UnpoweredOverlay.Visible = !power;
        if (!power)
        {
            EnterMainMenu();
        }
    }

    private void OnTextEdit()
    {
        ProgDoneButton.Disabled = string.IsNullOrWhiteSpace(NameEdit.Text) ||
                              NameEdit.Text.Length > 8 ||
                              !float.TryParse(TimeEdit.Text, out var time) ||
                              time < 0 || time > 9999 ||
                              !float.TryParse(TemperatureEdit.Text, out var temp) ||
                              temp < 65 || temp > 230 ||
                              ProgramList.Any(b => b.Text == NameEdit.Text);
    }

    private void OnProgramSelected(ItemList.ItemListSelectedEventArgs obj)
    {
        _selectedProgram = (GrillProgram)obj.ItemList[obj.ItemIndex].Metadata!;
        StartGrillButton.Disabled = false;
    }

    private void OnProgramDeselected(ItemList.ItemListDeselectedEventArgs obj)
    {
        _selectedProgram = null;
        StartGrillButton.Disabled = true;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        OnUpdateTime?.Invoke();
        OnUpdateOverlay?.Invoke();
        OnUpdatePower?.Invoke();
    }

    #region Menu openers
    public void EnterProgramEditor()
    {
        ProgramCreator.Visible = true;
        MainMenu.Visible = false;
    }

    public void EnterProgramSelector()
    {

        OnPopulatePrograms?.Invoke();
        ProgramSelector.Visible = true;
        MainMenu.Visible = false;
        StandbyScreen.Visible = false;
        AbortButton.Visible = true;
        GotItButton.Visible = false;
        CookingCountdown.Visible = false;
        _programCancelled = false;
    }

    public void EnterMainMenu()
    {
        ProgramCreator.Visible = false;
        StartGrillButton.Disabled = true;
        ProgramSelector.Visible = false;
        CookingCountdown.Visible = false;
        MainMenu.Visible = true;

    }

    public void EnterCooking()
    {
        MainMenu.Visible = false;
        ProgramSelector.Visible = false;
        CookingCountdown.Visible = true;
    }

    public void EnterStandbyWindow()
    {
        ProgramSelector.Visible = false;
        MainMenu.Visible = false;
        StandbyScreen.Visible = true;

    }

    public void EnterCancellation()
    {
        OnCookingCancelled?.Invoke();
        MainMenu.Visible = false;
        CookingCountdown.Visible = true;
        AbortButton.Visible = false;
        GotItButton.Visible = true;
        _programCancelled = true;
    }

    #endregion Menu openers
}
