using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.Access.Components;
using Content.Shared.CCVar;
using Content.Shared.Security.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Collard.Grill.UI;

[GenerateTypedNameReferences]
public sealed partial class ClamshellGrillMenu : FancyWindow
{
    [Dependency] private IConfigurationManager _cfgManager = default!;

    public event Action<string, float, float>? OnConfigurationComplete;

    public ClamshellGrillMenu(EntityUid owner, IEntityManager entMan)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);


        Title = entMan.GetComponent<MetaDataComponent>(owner).EntityName;

        NameLabel.SetMarkup(Loc.GetString("grill-ui-label-name"));
        SentenceLabel.SetMarkup(Loc.GetString("grill-ui-label-sentence"));
        CrimeLabel.SetMarkup(Loc.GetString("grill-ui-label-crime"));

        SentenceEdit.Text = "10";
        CrimeEdit.Text = "100";

        var maxIdJobLength = _cfgManager.GetCVar(CCVars.MaxIdJobLength);
        NameEdit.IsValid = val => !string.IsNullOrWhiteSpace(val) && val.Length <= maxIdJobLength;
        SentenceEdit.IsValid = val => float.TryParse(val, out var f) && f >= 0;
        CrimeEdit.IsValid = val => float.TryParse(val, out var f) && f >= 0;

        NameEdit.OnTextChanged += _ => OnTextEdit();
        SentenceEdit.OnTextChanged += _ => OnTextEdit();
        CrimeEdit.OnTextChanged += _ => OnTextEdit();

        DoneButton.OnPressed += _ =>
        {
            OnConfigurationComplete?.Invoke(NameEdit.Text, float.Parse(SentenceEdit.Text), float.Parse(CrimeEdit.Text));
        };
    }

    private void OnTextEdit()
    {
        DoneButton.Disabled = string.IsNullOrWhiteSpace(NameEdit.Text) ||
                              !float.TryParse(SentenceEdit.Text, out var sentence) ||
                              sentence < 0 ||
                              !float.TryParse(CrimeEdit.Text, out var crime) ||
                              crime < 0;
    }
}
