using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.Access.Components;
using Content.Shared.CCVar;
using Content.Shared.Collard.Grill;
using Content.Shared.Security.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Collard.Grill.UI;

[GenerateTypedNameReferences]
public sealed partial class ClamshellGrillMenu : FancyWindow
{
    [Dependency] private IConfigurationManager _cfgManager = default!;

    public event Action<string, float, float>? OnProgramConfigurationComplete;
    public event Action? OnPopulatePrograms;

    public ClamshellGrillMenu(EntityUid owner, IEntityManager entMan)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);


        Title = entMan.GetComponent<MetaDataComponent>(owner).EntityName;

        ProgramEditor.OnPressed += _ =>
        {
            ProgramCreator.Visible = true;
            MainMenu.Visible = false;
        };

        PressAndGo.OnPressed += _ =>
        {
            OnPopulatePrograms?.Invoke();
            ProgramSelector.Visible = true;
            MainMenu.Visible = false;
        };

        ProgBackButton.OnPressed += _ =>
        {
            ProgramCreator.Visible = false;
            MainMenu.Visible = true;
        };

        SelBackButton.OnPressed += _ =>
        {
            DeleteProgram.Disabled = true;
            StartGrillButton.Disabled = true;
            ProgramSelector.Visible = false;
            MainMenu.Visible = true;
        };

        NameLabel.SetMarkup(Loc.GetString("grill-ui-label-name"));
        TimeLabel.SetMarkup(Loc.GetString("grill-ui-label-time"));
        TemperatureLabel.SetMarkup(Loc.GetString("grill-ui-label-temp"));

        TimeEdit.Text = "10";
        TemperatureEdit.Text = "100";

        var maxIdJobLength = _cfgManager.GetCVar(CCVars.MaxIdJobLength);
        NameEdit.IsValid = val => !string.IsNullOrWhiteSpace(val) && val.Length <= maxIdJobLength;
        TimeEdit.IsValid = val => float.TryParse(val, out var f) && f >= 0;
        TemperatureEdit.IsValid = val => float.TryParse(val, out var f) && f >= 0;

        NameEdit.OnTextChanged += _ => OnTextEdit();
        TimeEdit.OnTextChanged += _ => OnTextEdit();
        TemperatureEdit.OnTextChanged += _ => OnTextEdit();
        ProgramList.OnItemSelected += _ =>
        {
            DeleteProgram.Disabled = false;
            StartGrillButton.Disabled = false;
        };
        ProgramList.OnItemDeselected += _ =>
        {
            DeleteProgram.Disabled = true;
            StartGrillButton.Disabled = true;
        };

        ProgDoneButton.OnPressed += _ =>
        {
            OnProgramConfigurationComplete?.Invoke(NameEdit.Text, float.Parse(TimeEdit.Text), float.Parse(TemperatureEdit.Text));
            ProgramCreator.Visible = false;
            MainMenu.Visible = true;
        };
    }

    /// <summary>
    /// Re-populates the list of grill programs available.
    /// </summary>
    public void Populate(IEnumerable<GrillProgram> programs)
    {
        ProgramList.Clear();

        foreach (var entry in programs)
        {
            ProgramList.AddItem(entry.Name, metadata: entry);
        }
    }

    private void OnTextEdit()
    {
        ProgDoneButton.Disabled = string.IsNullOrWhiteSpace(NameEdit.Text) ||
                              NameEdit.Text.Length > 8 ||
                              !float.TryParse(TimeEdit.Text, out var time) ||
                              time < 0 || time > 9999 ||
                              !float.TryParse(TemperatureEdit.Text, out var temp) ||
                              temp != 0 && temp < 65 || temp > 230 ||
                              ProgramList.Any(b => b.Text == NameEdit.Text);
    }

    // private void OnItemSelected()
    // {
    //     DeleteProgram.Disabled = string.IsNullOrWhiteSpace(NameEdit.Text) ||
    //                           NameEdit.Text.Length > 8 ||
    //                           !float.TryParse(TimeEdit.Text, out var time) ||
    //                           time < 0 || time > 9999 ||
    //                           !float.TryParse(TemperatureEdit.Text, out var temp) ||
    //                           temp != 0 && temp < 65 || temp > 230 ||
    //                           ProgramList.Any(b => b.Text == NameEdit.Text);
    // }
}
