- type: job
  id: Gatecrasher
  name: job-name-gatecrasher
  description: job-description-gatecrasher
  playTimeTracker: JobGatecrasher
  startingGear: GatecrasherGear
  icon: JobIconVisitor
  silentSpawn: true
  supervisors: job-supervisors-gatecrasher

- type: startingGear
  id: GatecrasherGear

- type: chameleonOutfit
  id: GatecrasherChameleonOutfit
  job: Gatecrasher
  equipment:
    head: ClothingHeadHatWelding
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckMantle
    outerClothing: ClothingOuterWinterCoat
    gloves: ClothingHandsGlovesColorYellowBudget
