- type: entity
  id: CrateDistressFlareImplants
  parent: CrateGenericSteel
  name: distress flare implants
  description: Contains a handful of distress flare implanters. A good way to mark your location when you are in danger.
  components:
  - type: StorageFill
    contents:
      - id: DistressFlareImplanter
        amount: 3
